#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
PATCH_NAME="CustomSignature"

TARGET_FILE="${PATCH_FOLDER}/smali_classes2/mcdonalds/dataprovider/apegroup/a.smali"

CUSTOM_SIGNATURE="this_is_a_test"

# Main function
function patch {
    sed -i "199aconst-string v1, \"${CUSTOM_SIGNATURE}\"" "${TARGET_FILE}"
}

info "Applying ${PATCH_NAME}..."
patch
