#!/usr/bin/env bash

#  Copyright 2019 Giacomo Ferretti
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Name of the patch
PATCH_NAME="AddMenuEntry"

MENU_ENTRY_ID="mod_offer_reset"
MENU_ENTRY_ID_DEC="2131361536"
MENU_ENTRY_ID_HEX="0x$(printf "%x" ${MENU_ENTRY_ID_DEC})"
MENU_ENTRY_TITLE="Reset"

TARGET_FILE_1="${PATCH_FOLDER}/smali_classes2/mcdonalds/loyalty/view/OfferDetailsActivity.smali"
TARGET_FILE_2="${PATCH_FOLDER}/res/values/ids.xml"
TARGET_FILE_3="${PATCH_FOLDER}/res/menu/menu_detail_view.xml"
TARGET_FILE_4="${PATCH_FOLDER}/res/values/public.xml"
TARGET_FILE_5="${PATCH_FOLDER}/smali_classes2/mcdonalds/loyalty/e\$f.smali"

PATCH_1="sget v1, Lmcdonalds/loyalty/e\$f;->${MENU_ENTRY_ID}:I
if-ne v0, v1, :cond_e

new-instance v1, Ljava/util/HashMap;
invoke-direct {v1}, Ljava/util/HashMap;-><init>()V

const-string v2, \"offer_id\"
iget-object v3, p0, Lmcdonalds/loyalty/view/OfferDetailsActivity;->j:Ljava/lang/String;
invoke-interface {v1, v2, v3}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

const-string v2, \"http://192.168.0.30:5000/reset_offer\"
invoke-static {v2, v1}, Lxyz/hexile/mcdapi/McdApi;->sendPostRequest(Ljava/lang/String;Ljava/util/Map;)V

sget-object v2, Ljava/lang/System;->out:Ljava/io/PrintStream;
invoke-virtual {v2, v3}, Ljava/io/PrintStream;->println(Ljava/lang/String;)V

invoke-virtual {p0}, Lmcdonalds/loyalty/view/OfferDetailsActivity;->finish()V

:cond_e"

CUR_FOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Main function
function patch {
    # Copy necessary smali files
    cp -rf "${CUR_FOLDER}/assets/"* "${PATCH_FOLDER}/smali/"

    sed -i "4755 a ${PATCH_1//$'\n'/\\n}" "${TARGET_FILE_1}"
    sed -i "729 a<item type=\"id\" name=\"${MENU_ENTRY_ID}\" />" "${TARGET_FILE_2}"
    sed -i "6 a<item android:id=\"@id/${MENU_ENTRY_ID}\" android:title=\"${MENU_ENTRY_TITLE}\" app:showAsAction=\"never\" />" "${TARGET_FILE_3}"
    sed -i "4937 a<public type=\"id\" name=\"${MENU_ENTRY_ID}\" id=\"${MENU_ENTRY_ID_HEX}\" />" "${TARGET_FILE_4}"
    sed -i "1072 a.field public static final ${MENU_ENTRY_ID}:I = ${MENU_ENTRY_ID_HEX}" "${TARGET_FILE_5}"
}

info "Applying ${PATCH_NAME}..."
patch
